GET http://localhost:4000/api/users HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4YzE4N2RkNWI5Y2FmM2YzNDlhMyIsImlzYWRtaW4iOmZhbHNlLCJpYXQiOjE2MzE2ODU5MDMsImV4cCI6MTYzMTY4NTkzM30.SqQaBB7jKhwRD9d5uEmBhVZ-Np-QR1L07W6E1l-fEXo



### LOGIN
POST http://localhost:4000/api/login HTTP/1.1
Content-Type: application/json

{
    "name":"zeynep",
    "username":"zeynep12",
    "password":"ba6ikha-"
}
### ADD USER
POST http://localhost:4000/api/register HTTP/1.1
Content-Type: application/json

{
   "name":"halil",
    "username":"halil12",
    "password":"ba6ikha-"
}
### GET PROFILE
GET http://localhost:4000/api/user/6142e354c706fccc1fe720c8 HTTP/1.1



### DELETE USER

DELETE http://localhost:4000/api/delete/6140b2ab268f2c7f4f56ad7c HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDE4YzE4N2RkNWI5Y2FmM2YzNDlhMyIsImlzYWRtaW4iOmZhbHNlLCJpYXQiOjE2MzE2ODU5MDMsImV4cCI6MTYzMTY4NTkzM30.SqQaBB7jKhwRD9d5uEmBhVZ-Np-QR1L07W6E1l-fEXo
### REFERESH TOKEN

POST http://localhost:4000/api/login/refresh HTTP/1.1
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxM2U5OGUxMzQ5OTViZTY3ZDRlMTAxMCIsImlzYWRtaW4iOnRydWUsImlhdCI6MTYzMTY0NDgzOX0.jw4iek30CjmZDMsPePjsqZd8n43S9UXA75wAQ2yE7WU"
}
### log out
POST http://localhost:4000/api/logout HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNDA0Njg4MjZjMTk5NjhmZjE4MDM4OSIsImlzYWRtaW4iOmZhbHNlLCJpYXQiOjE2MzE2MDg0ODAsImV4cCI6MTYzMTYwODUxMH0.hpIyNhcXBs64YFEiwUcsCptX7kXB3w6ILmMI3rr1FiE